### ISSUE TITLE
Extracting the median

### ISSUE THREAD

**Issue by MetaColon** [MetaColon/PfN-Project#6]
The median is the value from the sample that is the _middle_ value, if the samples are presented in order.

**Comment by Hneuschmidt** [comment]
I added the basic median function for arrays of type double (this can be trivially changed)
In what form will the data arrive here, and should the sorting be done at this moment?
Right now the function assumes an already sorted array.

**Comment by MetaColon** [comment]
@Hneuschmidt I think it'll be helpful to at least provide the option to sort the array (maybe via an extra parameter). However, as this is a prototype it's not important.
