### ISSUE TITLE
Confidence intervals

### ISSUE THREAD

**Issue by MetaColon** [MetaColon/PfN-Project#7]
Evaluating the confidence intervals is the main task of the project. Given a percentage of confidence (e.g. 95%), a range should be returned in which e.g. 95% of the values can be found.

**Comment by MetaColon** [comment]
We need a better way to evaluate confidence interval. One way to do this (not to say the only one), is by starting from the median and increasing the size of the interval, until 95% (or any other rate) of the values is in the interval.

**Comment by Jubi72** [comment]
> We need a better way to evaluate confidence interval. One way to do this (not to say the only one), is by starting from the median and increasing the size of the interval, until 95% (or any other rate) of the values is in the interval.

Yeah, you know, got another quite short way by calculating the position of the elements in the sorted data array holding the minimum and the maximum of the confidence interval. You can see the calculation in the code added in Commit 7ef91c5.

**Comment by MetaColon** [comment]
@Jubi72 I don't think that works. If the values are unevenly distributed, your left bound might be way lower than your right bound (because you take the same amount of values to the left of the median as to the right). However, the confidence interval (if I understood it correctly), should be a range that's centered at the medium (not the median, another potential problem).

**Comment by Jubi72** [comment]
> However, the confidence interval should be a range that's centered at the medium.

Okay, so here's an example why I think you're wrong. 

Assume you have one million values of 0 and one value of one trillion (10^12). Then the median is 0 and the medium is 999,999.

Why should the confidence interval be centered to the medium? It's far better to say that 99.9 % of the values lie in [0;0] than to say they're in [0;10^12] when it's only one value enforcing that.

I don't know about you, but
> I only believe in statistics that I doctored myself.
_- Winston S. Churchill (probably nazi propaganda, but that's not my point)_

PS: Maybe sometime I will read the documents our professor made available to us and give you a quote of them to prove you wrong.

**Comment by MetaColon** [comment]
@Jubi72 It seems as if I concluded that the confidence interval has to be centered at the medium too quickly, as the confidence interval always is just for a certain parameter of choice - one can _choose_ to center it at the medium, but one can also choose to center it at the median.

I guess wether it's better to choose the medium or the median is debatable (I still prefer the medium, but maybe that's just personal taste - I think it's always possible to find an abstruse example in which the matter of choice seems dumb), but my original point remains valid: even if not centered at the medium, it still has to be _centered_ (the official definitions confuse me quite a bit on that front, but this is at least intuitively reasonable and seems to be in line with examples).

So whilst your confidence is centered in the _array_ of data, you could (for unevenly distributed data, which seems far more likely than your example) get an interval of the form [1,5] for a median (or medium, whatever) of 4, whereas I would expect a confidence interval of [2,6].

What I'm trying to say is that your using the _elements_ of the array, whereas I would expect the _values_ of the array to be used. I'm not sure I expressed my point understandably, so maybe we'll have to talk about this in person (or as close as it gets nowadays).

**Comment by MetaColon** [comment]
Let's give a (rather extreme) example. Consider the array `0.1, 0.2, 0.3, 0.4, 100, 200, 300` (note that this is just to illustrate my point, I'm sure there are more reasonable examples that lead to the same problem).

The median would then be 0.4 and (for some certainty level) your method would yield [0.3, 100] (which is clearly not centered at 0.4), but I would expect [0.2, 0.6].

**Comment by MetaColon** [comment]
I think we can bury this (at least for now)
